### ISSUE TITLE
Two Day Events Only Appear on the First Day

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/tec-ical-importer#14]
I've set an event at this public link called Connect Conference on the 7th and 8th. 

https://outlook.office365.com/owa/calendar/bf003a1abcf84b0aa9e9efc5dbdacc29@hwdsb.on.ca/7a59952a20c74cf891ea03f574c6015c16473069629035088643/calendar.ics

On the calendar at http://sandbox.commons.hwdsb.on.ca/events, that event appears only on the 7th.

**Comment by mrjarbenne** [comment]
It looks like it might be an issue with recurring events. A two week event on this feed: 

https://outlook.office365.com/owa/calendar/bf003a1abcf84b0aa9e9efc5dbdacc29@hwdsb.on.ca/07bb9e1d6402448e8a681167e17364ed12200477414055768439/calendar.ics

Occuring from December 21st to January 1st is not listed on the 1st. 

This calendar has been synced using the plugin on http://sandbox.commons.hwdsb.on.ca/events

**Comment by r-a-y** [comment]
I need to look for a more universal solution for those living east of Greenwich, but this should fix this issue for our needs.
