### ISSUE TITLE
Compatibility with latest version of Events Calendar

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/tec-ical-importer#15]
I started a sync a few days ago. It looks as if events in the past are being duplicated. Note also the lack of an author on the automatically created past events

http://www.screencast.com/t/vcAxG6I50

Aside: This plugin was created to fit a functionality that didn't previously exist. ModernTribe has recently released their own version of this functionality. It might be worth the $350 to stop development on this and adopt their solution. That said, I'm not sure theirs has the same ability to add categories, which is something we use. It would require further research, but I'm putting it out there as an option https://theeventscalendar.com/product/ical-importer/

**Comment by r-a-y** [comment]
Do you have a lot of iCal links due for syncing?  Can you copy all the iCal links from that site and send them to my email?

I'll know more when I test locally.

About Modern Tribe's version, it looks like their version has support for categories.  Using their version would mean having to re-add the iCal links throughout all sites unless I build a small importer.

When I fix this bug, it might not be worth using their version unless their version has a ton more features that would equal more development time on my end.

**Comment by r-a-y** [comment]
So Modern Tribe has done a bunch of changes to their plugin... have to look what they've done.

More to come.

**Comment by r-a-y** [comment]
About the duplication, it appears that the Outlook iCal file is adding these events one at a time; It doesn't appear to be duplicating.

Only the "Winter Holiday" and "March Break" events are marked as recurring.

However, importing the recurrence data is currently broken at the moment and I'm looking into it.  Modern Tribe made some changes here so I need to update the code.

**Comment by mrjarbenne** [comment]
Sorry, Yes, those events have been added one at a time, Day 1-5, up until June. Perhaps that's not the easiest file to use as a sample. If you look in the sandbox.commons.hwdsb.on.ca/events theme, you will notice that events in the past are repeated, so in the future there is only one "Day 1" for example, but once the date passes, the events in the past begin to replicate, so every day the sync happens, another "Day 1" in the past is created. Perhaps you can see it more clearly on bblog.commons.hwdsb.on.ca. I've been cleaning that one up by going in occasionally and deleting, but the idea is there:

![2015-10-09_16-19-08](https://cloud.githubusercontent.com/assets/480667/10404573/a83ac8da-6ea1-11e5-8e43-d1428965950f.png)

**Comment by r-a-y** [comment]
Duplication should be fixed on master.  Unfortunately, at the moment, existing duplicated events will need to be cleaned up manually unless I write a script to clean them up.

I'm currently working on getting recurrence fixed.

**Comment by mrjarbenne** [comment]
I can clean up the duplicates. I know where most of them are from bug reports.

**Comment by r-a-y** [comment]
This should be fixed now.  Please give it a test when you have a chance.
