### ISSUE TITLE
Import Not Working

### ISSUE THREAD

**Issue by darknailblue** [hwdsbcommons/tec-ical-importer#16]
After downloading and installing the plugin, the import isn't working at all.  After checking the manual sync and saving, there is a notification that the iCalendars were successfully parsed but no events are actually imported.

What should I do?

**Comment by r-a-y** [comment]
Thanks for the report.

The plugin relies on the SG-iCalendar library, which uses cURL to download iCalendar URL:
https://github.com/hwdsbcommons/tec-ical-importer/blob/master/includes/SG-iCalendar/helpers/SG_iCal_Parser.php#L41

Check if cURL is installed on your server.

Also, check if there are any errors in your server log by setting `WP_DEBUG` to true in `wp-config.php` and re-running the manual import:
https://codex.wordpress.org/WP_DEBUG
