### ISSUE TITLE
Some events not importing

### ISSUE THREAD

**Issue by alexwinfield** [hwdsbcommons/tec-ical-importer#17]
There are several events in the .ics file for August that aren't being imported onto the calendar for some reason: http://myglenville.com/events/2016-08/

The events are display fine in the public calendar ics file and in Outlook when I import them there.  Can you assist?

Public calendar file: https://calendar.google.com/calendar/ical/un37quboqcpv0qkubcl1ivdgo8%40group.calendar.google.com/public/basic.ics

[basic (4).zip](https://github.com/hwdsbcommons/tec-ical-importer/files/390831/basic.4.zip)

**Comment by alexwinfield** [comment]
FYI - using Event Cal Version 4.2.3

**Comment by alexwinfield** [comment]
Read the archive (probably should've done that first ;-P) and installed Event Cal Pro.  After bulk deleting all events and syncing them again, still no luck :-/

**Comment by mrjarbenne** [comment]
Are you seeing any pattern regarding which events are showing and which are not syncing? I did a quick sync of that ics link you provided and it pulled in 1608 events. Depending on your server set up, that might result in a timeout that would omit events. 

If you can look for a pattern ie: only recurring events, only full day events, multiple day events etc. it might be easier to triage. The plugin is working fine on our install, but our ics source is Office365, not Google Calendar, so you may have found a bug related to the Google ics feed.

**Comment by mrjarbenne** [comment]
Given the lack of response, I'm closing this.
