### ISSUE TITLE
Events that Aren't Full Day not Importing Correctly

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/tec-ical-importer#18]
Full day events are working fine, but events that are set for a specific time are not getting pulled in correctly, and are appearing in the dashboard as if they are scheduled for December 31st 1969

![2016-09-19_20-13-51](https://cloud.githubusercontent.com/assets/480667/18653102/a332d278-7ea5-11e6-9c9f-358f5d17cc1d.png)

Here's the public feed I'm using: 
https://outlook.office365.com/owa/calendar/bf003a1abcf84b0aa9e9efc5dbdacc29@hwdsb.on.ca/f778ecb87bee421aaa406e32150e9b961591139407450592570/calendar.ics

The events are being pulled in on https://sandbox.commons.hwdsb.on.ca/events/category/hub/

Although 4 events were entered in September 2016, only the full day event is appearing on the calendar correctly

**Comment by mrjarbenne** [comment]
Looks like they were dealing with the same thing, but fixed it in their import plugin. Too bad we don't have access to their changelog to see what the issue was: 

https://theeventscalendar.com/release-the-events-calendar-4-1-3-and-premium-add-ons/

![2016-09-19_20-26-33](https://cloud.githubusercontent.com/assets/480667/18653368/63e46788-7ea7-11e6-82a7-b1be686ac6d3.png)

**Comment by r-a-y** [comment]
Looking into this now.

Appears to be an Outlook issue where they are adding an invalid timezone and is causing problems with the iCalendar parser.  More to come.

**Comment by r-a-y** [comment]
I think I've fixed the issue.

Current events will need to be removed and resynced to take effect for the iCal(s) in question.

**Comment by mrjarbenne** [comment]
Thanks. Enjoy the the long weekend.

**Comment by r-a-y** [comment]
You too!
